# python - base container name
# alpine - container tag
FROM python:alpine

# create app dir in container(best practice)
WORKDIR /app

# copy all to WORKDIR
COPY . .

# run command when container is created(on run)
CMD ["python", "main.py"]